---
- name: "openssh | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "openssh | Include authorized keys command tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/openssh_authorized_keys_command.yml"
  when:
    - "lookup('ansible.builtin.vars',
      'openssh_settings_authorized_keys_command_content',
      default='') not in ['', [], '[]', None]"
- name: "openssh | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/openssh.yml"
  when:
    - "lookup('ansible.builtin.vars', 'openssh_sshd_settings',
      default='') not in ['', [], '[]', None]"
