---
- name: "openssh | Restart systemd service"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['openssh_service'] }}"
    state: "{{ lookup('ansible.builtin.vars', 'openssh_restart_cmd') }}"
  listen: "Reload openssh daemon"
  when:
    - "hostvars[inventory_hostname]['openssh'] is defined"
    - "hostvars[inventory_hostname]['openssh'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['openssh'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'openssh_restart', default='')) == 'true'"
  vars:
    openssh_restart: "[] | map(&restart || 'false', @) | [0]"
